on:
  push:
    branches: [main]

jobs:
  # Deploy job
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          artifact_name: dist
